// export type Json =
//   | string
//   | number
//   | boolean
//   | null
//   | { [key: string]: Json | undefined }
//   | Json[]

// export interface Database {
//   public: {
//     Tables: {
//       profiles: {
//         Row: {
//           id: string
//           username: string
//           full_name: string | null
//           avatar_url: string | null
//           bio: string | null
//           created_at: string
//           updated_at: string
//         }
//         Insert: {
//           id: string
//           username: string
//           full_name?: string | null
//           avatar_url?: string | null
//           bio?: string | null
//           created_at?: string
//           updated_at?: string
//         }
//         Update: {
//           id?: string
//           username?: string
//           full_name?: string | null
//           avatar_url?: string | null
//           bio?: string | null
//           created_at?: string
//           updated_at?: string
//         }
//       }
//       posts: {
//         Row: {
//           id: string
//           user_id: string
//           content: string | null
//           media_url: string | null
//           type: 'photo' | 'thought'
//           created_at: string
//           updated_at: string
//         }
//         Insert: {
//           id?: string
//           user_id: string
//           content?: string | null
//           media_url?: string | null
//           type: 'photo' | 'thought'
//           created_at?: string
//           updated_at?: string
//         }
//         Update: {
//           id?: string
//           user_id?: string
//           content?: string | null
//           media_url?: string | null
//           type?: 'photo' | 'thought'
//           created_at?: string
//           updated_at?: string
//         }
//       }
//     }
//   }
// }

// types/supabase.ts
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string; // UUID
          email: string; // User's email address
          password_hash: string; // Hashed password
          username: string; // Unique username
          created_at: string; // Timestamp of account creation
          updated_at: string; // Timestamp of last update
        };
        Insert: {
          id?: string; // Optional, can be autogenerated
          email: string; // Required email
          password_hash: string; // Required hashed password
          username: string; // Required unique username
          created_at?: string; // Optional, autogenerated
          updated_at?: string; // Optional, autogenerated
        };
        Update: {
          id?: string;
          email?: string;
          password_hash?: string;
          username?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
}